### ISSUE TITLE
How to use <?= and <?php

### ISSUE THREAD

**Issue by schmunk42** [cmrcx/phptidy#9]
I'd like to keep `<?=` but not to use short open tags `<?`.
I saw the global variable `open_tag`, but I think it affects both.

Even, if possible, I'd like to rewrite `<?php echo` to `<?=`.

**Comment by cmrcx** [comment]
I see that the behavior has changed since PHP 5.4: http://php.net/manual/en/ini.core.php#ini.short-open-tag

But I don't understand what sense it makes to use short tags only for the echo case. Can you explain?

Do you have an idea how to add this as a backward compatible option? My idea so far is one option for keeping open-echo-short-tags even in combination with long open tags and one option for converting open tags with following echo to shorthand tags. But this is not an elegant solution.

**Comment by schmunk42** [comment]
> But I don't understand what sense it makes to use short tags only for the echo case. Can you explain?

It's simply much easier to read.

The conversion from `<?php echo` from `<?=` might be tricky. But to keep existing open-echo-short-tag by using a new option sounds fine to me.
